### ISSUE TITLE
Support for react 15? 

### ISSUE THREAD

**Issue by julianljk** [StevenIseki/react-tab-view#3]
Will this continue to be supported with the new version of react?

**Comment by StevenIseki** [comment]
I am hoping to update all of my components this weekend to be compatible with latest version of react.

**Comment by stephenmathieson** [comment]
any word?

**Comment by Flurb** [comment]
Will be appreciated yes :)

**Comment by StevenIseki** [comment]
@Flurb @stephenmathieson @julianljk 
Sorry a bit later, but support now for react v 15.0. 
Will be updating all my react components over the next week, also to using enzyme for testing.
No major update otherwise, if you want any new features feel free to ask.
Also you should star this component if it is so important for you, it only has 4 stars ⭐ :)
